# Generated by Django 2.1.5 on 2019-01-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtask',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasktransaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
