# Generated by Django 2.1.5 on 2019-01-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering', '0002_auto_20190119_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
